"""Generate a recognition prior from the authoritative pallet geometry YAML."""

import argparse
from pathlib import Path

import yaml

from forklift_core.perception.pallet_geometry import load_pallet_geometry

# The catalogue v1 pallet's opening height, the same anchor the detector's
# parameter derivation uses. Keeping one anchor means a shape's prior and its
# parameters shrink together rather than drifting apart.
ANCHOR_OPENING_HEIGHT_M = 0.20


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--geometry", type=Path, required=True)
    parser.add_argument("--output", type=Path, help="Prior YAML path; default: stdout")
    parser.add_argument(
        "--opening-width-tolerance",
        type=float,
        default=0.02,
        help="Symmetric opening-width tolerance in metres (default: 0.02)",
    )
    parser.add_argument(
        "--centre-spacer-tolerance",
        type=float,
        default=0.015,
        help="Symmetric centre-spacer tolerance in metres (default: 0.015)",
    )
    parser.add_argument(
        "--scale-tolerances",
        action="store_true",
        help="Scale both tolerances by this pallet's opening height against the "
        "catalogue v1 pallet's 200 mm, instead of using the absolute defaults. "
        "The defaults are absolute, so they loosen as the shape shrinks: "
        "+/-15 mm is 10.3 %% of EPAL 6's centre spacer but 18.8 %% of "
        "T11 x0.6's, which is the shape with the least evidence to spare.",
    )
    args = parser.parse_args(argv)
    geometry = load_pallet_geometry(args.geometry)
    if args.scale_tolerances:
        scale = geometry.block_height_m / ANCHOR_OPENING_HEIGHT_M
        args.opening_width_tolerance *= scale
        args.centre_spacer_tolerance *= scale
    prior = geometry.to_pallet_prior(
        opening_width_tolerance_m=args.opening_width_tolerance,
        centre_spacer_tolerance_m=args.centre_spacer_tolerance,
    )
    data = {
        "source_provenance": prior.source_provenance,
        "catalogue_version": prior.catalogue_version,
        "height_m": prior.height_m,
        "deck_bottom_m": prior.deck_bottom_m,
        "deck_top_m": prior.deck_top_m,
        "opening_height_m": prior.opening_height_m,
        "opening_width_range": [prior.opening_width_min_m, prior.opening_width_max_m],
        "centre_spacer_range": [prior.centre_spacer_min_m, prior.centre_spacer_max_m],
        "overall_width_m": prior.overall_width_m,
        "overall_depth_m": prior.overall_depth_m,
        "opening_width_tolerance_m": args.opening_width_tolerance,
        "centre_spacer_tolerance_m": args.centre_spacer_tolerance,
    }
    # Suppress binary-float representation noise, retaining picometre precision.
    data = {
        key: [round(x, 12) for x in value]
        if isinstance(value, list)
        else round(value, 12)
        if isinstance(value, float)
        else value
        for key, value in data.items()
    }
    text = (
        "# Generated by tools/build_pallet_prior.py; edit the geometry source.\n"
        "# See source_provenance; not measured delivered-pallet dimensions.\n"
        + yaml.safe_dump(data, sort_keys=False)
    )
    if args.output is None:
        print(text, end="")
    else:
        args.output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
